# This rule is not used by the project netchaos itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the nettools.amirrazmjou.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: netchaos
    app.kubernetes.io/managed-by: kustomize
  name: icmpdroprule-editor-role
rules:
- apiGroups:
  - nettools.amirrazmjou.com
  resources:
  - icmpdroprules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nettools.amirrazmjou.com
  resources:
  - icmpdroprules/status
  verbs:
  - get
