---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nettools.amirrazmjou.com
  resources:
  - icmpdroprules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nettools.amirrazmjou.com
  resources:
  - icmpdroprules/finalizers
  verbs:
  - update
- apiGroups:
  - nettools.amirrazmjou.com
  resources:
  - icmpdroprules/status
  verbs:
  - get
  - patch
  - update
